const classicTrilogy = "Trilogia Clássica"
const prequelTrilogy = "Trilogia Prequel"
const spinoff = "Spin- Off"
const newTrilogy = "Trilogia nova"

const movies = [
{nome:"Uma Nova Esperança",sinopse:"Conta a história do jovem fazendeiro Luke Skywalker (Mark Hamill), que, após adquirir dois droids (robôs), envolve-se na Guerra Civil Galáctica entre o tirano Império Galáctico e a Aliança Rebelde, ao lado do contrabandista Han Solo (Harrison Ford). Um dos robôs contém na memória o projeto secreto da super arma do Império, Estrela da Morte, roubado pelos rebeldes e inserido no droid por sua líder, Princesa Leia (Carrie Fisher), que com isso espera destruir o Império e salvar a galáxia.", ano:1977, ordenacao:1, secao:classicTrilogy, imagem:"https://bit.ly/2TIetq4"},
{nome:"O Império Contra Ataca",sinopse:"O filme é ambientado três anos depois de Guerra nas Estrelas. O Império Galáctico, sob a liderança do vilão Darth Vader e do misterioso Imperador, está em busca de Luke Skywalker e o resto da Aliança Rebelde. Enquanto Vader procura incansavelmente o pequeno grupo de amigos de Luke — Han Solo, Princesa Leia Organa e outros — através da galáxia, Luke é ensinado pelo Mestre Yoda a como usar a Força. Quando Vader captura os amigos de Luke, Luke deve decidir se vai completar seu treinamento e se tornar um Cavaleiro Jedi completo ou confrontar Vader e salvá-los.", ano:1980,ordenacao:2,secao:classicTrilogy,imagem:"https://bit.ly/2TIetq4"},
{nome:"O retorno Jedi",sinopse:"A história se passa aproximadamente um ano depois dos eventos de Star Wars Episode V: The Empire Strikes Back.[7] O Império Galático, sob a supervisão militar do impiedoso Darth Vader, começou a construção de uma segunda Estrela da Morte, visando aniquilar a Aliança Rebelde. Como o Imperador Palpatine, também conhecido como Darth Sidious, planeja supervisionar pessoalmente as etapas finais de sua construção, a Frota Rebelde dá início a um ataque em grande escala à Estrela da Morte, para evitar o término de sua construção e matar Palpatine, pondo efetivamente um fim ao Império. Neste meio tempo, Luke Skywalker, um líder rebelde e cavaleiro jedi, luta para resgatar Vader, um ex-jedi que também é seu pai, de volta do Lado Sombrio da Força.", ano:1982,ordenacao:3,secao:classicTrilogy,imagem:"https://bit.ly/3cNern8"},
{nome:"A Ameaça Fantasma",sinopse:"Ameaça Fantasma ocorre cerca de 32 anos antes do filme original, e segue o Mestre Jedi Qui-Gon Jinn e seu padawan Obi-Wan Kenobi, como protetores da Rainha Amidala, na esperança de conseguir um fim pacífico para uma disputa comercial interplanetária de grande escala. Em sua jornada juntam-se a eles Anakin Skywalker—um jovem escravo com forte conexão com a Força—simultaneamente com o retorno dos misteriosos Sith.", ano:1993,ordenacao:4,secao:prequelTrilogy,imagem:"https://bit.ly/3xsioFX"},
{nome:"Ataque dos Clones",sinopse:"O filme ocorre 10 anos após os acontecimentos de Star Wars Episódio I: A Ameaça Fantasma. A galáxia está à beira de uma guerra civil. Liderado por um ex-Jedi chamado Conde Dooku, milhares de sistemas planetários ameaçam deixar a República Galáctica. Após a senadora Padmé Amidala escapar de uma tentativa de assassinato, Anakin Skywalker, um aprendiz Jedi, se torna seu protetor, enquanto seu mestre Obi-Wan Kenobi, investiga o atentado contra a vida dela. Logo Anakin, Padmé, e Obi-Wan testemunham o início de uma nova ameaça à galáxia, as Guerras Clônicas.", ano:2002,ordenacao:5,secao:prequelTrilogy,imagem:"https://bit.ly/3vur0ud"},
{nome:"A Vingança dos Sith",sinopse:"O filme começa três anos após o início das Guerras Clônicas. Os Cavaleiros Jedi estão espalhados por toda a galáxia, liderando uma guerra maciça contra os Separatistas. O Conselho Jedi incumbe o Mestre Jedi Obi-Wan Kenobi de eliminar o notório General Grievous, líder do Exército Separatista. Enquanto isto, o Cavaleiro Jedi Anakin Skywalker se aproxima de Palpatine, o Supremo Chanceler da República Galáctica e, desconhecido do público, um Lord Sith. Sua amizade aprofundada ameaça a Ordem Jedi, a República, e o próprio Anakin.", ano:2005,ordenacao:6,secao:prequelTrilogy,imagem:"https://bit.ly/35qWXZJ"},
{nome:"Rogue One",sinopse:"A narrativa de Rogue One: A Star Wars Story é estabelecida entre os acontecimentos de A Vingança dos Sith e Uma Nova Esperança. A história do filme se baseia em um grupo de combatentes da Aliança Rebelde se unindo para uma missão de roubar os planos da Estrela da Morte.", ano:2016,ordenacao:7,secao:spinoff,imagem:"https://bit.ly/3guHP44"},
{nome:"Han Solo",sinopse:" O filme se passa dez anos antes dos acontecimentos em Star Wars e explora as primeiras aventuras de Han Solo e Chewbacca, incluindo o personagem Lando Calrissian.", ano:2018,ordenacao:8,secao:spinoff,imagem:"https://bit.ly/3iOIa34"},
{nome:"O Despertar da Força",sinopse:"O Despertar da Força se passa aproximadamente trinta anos após os acontecimentos de Return of the Jedi, e acompanha a jornada de Rey, que acaba encontrando um droide, BB-8, com informações do paradeiro de Luke Skywalker que está desaparecido. Ela é acompanhada por Finn, um stormtrooper desertor da Primeira Ordem, uma organização que quer reaver o Império Galáctico e luta contra a Resistência, comandada por Leia Organa. A aventura inesperada leva Rey a descobrir sua forte conexão com a Força e enfrentar o Lado Sombrio.", ano:2015,ordenacao:9,secao:newTrilogy ,imagem:"https://bit.ly/3zsIzOJ"},
{nome:"Os Últimos Jedi",sinopse:"Integrantes da Resistência liderados pela general Leia Organa abandonam sua base principal quando uma frota da Primeira Ordem alcança o planeta onde eles estão. Após a batalha, as naves da Resistência fogem na velocidade da luz. Leia repreende Poe Dameron por um contra-ataque que, embora bem-sucedido, causou a perda de muitas vidas e naves; ao mesmo tempo, o Líder Supremo Snoke repreende o General Hux por ter deixado a Resistência escapar. Hux, entretanto, está usando um rastreador que consegue seguir naves na velocidade da luz, e inicia uma perseguição com a Resistência, que consegue manter distância, mas o combustível das naves, que também mantém o funcionamento dos escudos, está perto de acabar.", ano:2017,ordenacao:10,secao:newTrilogy ,imagem:"https://bit.ly/3xvaPhw"},
{nome:"A Ascenção de Skywalker",sinopse:"O filme começa com Kylo Ren aniquilando um grupo de cultistas Sith em Mustafar para obter um localizador que revelaria onde está o ressuscitado Imperador Palpatine. Após obter o localizador Sith, ele o usa para guiá-lo até o Imperador no planeta Exegol, para matá-lo, já que não quer nenhuma ameaça ao seu poder. Exegol está cheio de cultistas Sith de Palpatine. Este revela que criou Snoke e que tem sido as vozes que levaram Kylo ao Lado Sombrio. O Imperador oferece um novo império a ele, para governar a galáxia inteira, com a condição de que Kylo matasse Rey.", ano:2019,ordenacao:11,secao:newTrilogy ,imagem:"https://bit.ly/3vx59lS"}
]

module.exports = movies